[project]
name = "chew"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aku>=0.2.6",
    "numpy>=2.2.6",
    "orjson>=3.11.4",
    "tabulate>=0.9.0",
]
